#!/bin/sh

# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

### ONLY FOR 
cd system/
echo "Creating blockMesh file..."
python3 blockMeshGenerator.py
echo "blockMesh file created."
cd ..

echo "Running blockMesh..."
blockMesh
echo "blockMesh complete."

echo "Running surfaceFeatures..."
surfaceFeatures
echo "surfaceFeatures complete."

echo "Running snappyHexMesh..."
snappyHexMesh -overwrite 
echo "snappyHexMesh complete."

### RUNNING SIMULATIONS
echo "Running simpleFoam..."
simpleFoam
echo "Simulation complete."

cd system/
echo "Generating probes..."
python3 probesGenerator.py
echo "Probe generation complete."
cd ..

# postProcess -func probes1 -time 100
# postProcess -func probes2 -time 100
# postProcess -func probes3 -time 100

# postProcess -func probes1 -time 200
# postProcess -func probes2 -time 200
# postProcess -func probes3 -time 200

# postProcess -func probes1 -time 300
# postProcess -func probes2 -time 300
# postProcess -func probes3 -time 300

postProcess -func probeComparison -time 200

# echo "Opening paraFoam..."
# paraFoam
# echo "paraFoam opened."

# # example running toposet and refinemesh 3 times with multiple dictionaries
# # -a|-append option appends to log file
# i=0
# while [ "$i" -lt 3 ]
# do
#     runapplication -a toposet -dict "toposetdict.${i}"
#     runapplication -a refinemesh -dict "refinemeshdict.${i}"
#     i=$(( i + 1))
# done

# runapplication decomposepar

# # example with runparallel to run in parallel
# # getapplication finds solver name from "application" entry in controldict
# runparallel "$(getapplication)"

# runapplication reconstructpar

#------------------------------------------------------------------------------

echo "Finished, no errors."