#!/bin/sh

# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

### ONLY FOR 
# cd system/
# echo "Creating blockMesh file..."
# python3 blockMeshGenerator.py
# echo "blockMesh file created."
# cd ..

# echo "Running blockMesh..."
# runApplication blockMesh
# echo "blockMesh complete."

# echo "Running surfaceFeatures..."
# runApplication surfaceFeatures
# echo "surfaceFeatures complete."

# echo "Running snappyHexMesh..."
# runApplication snappyHexMesh -overwrite 
# echo "snappyHexMesh complete."

### RUNNING SIMULATIONS
echo "Running simpleFoam..."
simpleFoam
echo "Simulation complete."

cd system/
echo "Generating probes..."
python3 probesGenerator.py
echo "Probe generation complete."
cd ..

postProcess -func probes1 -latestTime
postProcess -func probes2 -latestTime
postProcess -func probes3 -latestTime

echo "Opening paraFoam..."
runApplication paraFoam
echo "paraFoam opened."

# # example running toposet and refinemesh 3 times with multiple dictionaries
# # -a|-append option appends to log file
# i=0
# while [ "$i" -lt 3 ]
# do
#     runapplication -a toposet -dict "toposetdict.${i}"
#     runapplication -a refinemesh -dict "refinemeshdict.${i}"
#     i=$(( i + 1))
# done

# runapplication decomposepar

# # example with runparallel to run in parallel
# # getapplication finds solver name from "application" entry in controldict
# runparallel "$(getapplication)"

# runapplication reconstructpar

#------------------------------------------------------------------------------

echo "Finished, no errors."